package com.path.alert.vo.omniservice;

import java.math.BigDecimal;
import java.util.Date;

public class ALRT_PUSH_NOTIFICATIONVO extends ALRT_PUSH_NOTIFICATIONVOKey {
    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.NOTIFICATION_DEVICE_TOKEN_ID
     */
    private BigDecimal NOTIFICATION_DEVICE_TOKEN_ID;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.COMP_CODE
     */
    private BigDecimal COMP_CODE;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.APP_ID
     */
    private BigDecimal APP_ID;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.CHNL_ID
     */
    private BigDecimal CHNL_ID;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.TITLE
     */
    private String TITLE;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.BODY
     */
    private String BODY;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.LANDING_PAGE
     */
    private String LANDING_PAGE;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.NOTIFICATION_DATA
     */
    private String NOTIFICATION_DATA;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.STATUS
     */
    private String STATUS;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.CHANNEL_USER_ID
     */
    private BigDecimal CHANNEL_USER_ID;
    
    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.CHANNEL_USER_NAME
     */
    private String CHANNEL_USER_NAME;

    /**
     * This field corresponds to the database column ALRT_PUSH_NOTIFICATION.CREATED_DATE
     */
    private Date CREATED_DATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.NOTIFICATION_DEVICE_TOKEN_ID
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.NOTIFICATION_DEVICE_TOKEN_ID
     */
    public BigDecimal getNOTIFICATION_DEVICE_TOKEN_ID() {
        return NOTIFICATION_DEVICE_TOKEN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.NOTIFICATION_DEVICE_TOKEN_ID
     *
     * @param NOTIFICATION_DEVICE_TOKEN_ID the value for ALRT_PUSH_NOTIFICATION.NOTIFICATION_DEVICE_TOKEN_ID
     */
    public void setNOTIFICATION_DEVICE_TOKEN_ID(BigDecimal NOTIFICATION_DEVICE_TOKEN_ID) {
        this.NOTIFICATION_DEVICE_TOKEN_ID = NOTIFICATION_DEVICE_TOKEN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.COMP_CODE
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.COMP_CODE
     */
    public BigDecimal getCOMP_CODE() {
        return COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.COMP_CODE
     *
     * @param COMP_CODE the value for ALRT_PUSH_NOTIFICATION.COMP_CODE
     */
    public void setCOMP_CODE(BigDecimal COMP_CODE) {
        this.COMP_CODE = COMP_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.APP_ID
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.APP_ID
     */
    public BigDecimal getAPP_ID() {
        return APP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.APP_ID
     *
     * @param APP_ID the value for ALRT_PUSH_NOTIFICATION.APP_ID
     */
    public void setAPP_ID(BigDecimal APP_ID) {
        this.APP_ID = APP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.CHNL_ID
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.CHNL_ID
     */
    public BigDecimal getCHNL_ID() {
        return CHNL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.CHNL_ID
     *
     * @param CHNL_ID the value for ALRT_PUSH_NOTIFICATION.CHNL_ID
     */
    public void setCHNL_ID(BigDecimal CHNL_ID) {
        this.CHNL_ID = CHNL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.TITLE
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.TITLE
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.TITLE
     *
     * @param TITLE the value for ALRT_PUSH_NOTIFICATION.TITLE
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE == null ? null : TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.BODY
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.BODY
     */
    public String getBODY() {
        return BODY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.BODY
     *
     * @param BODY the value for ALRT_PUSH_NOTIFICATION.BODY
     */
    public void setBODY(String BODY) {
        this.BODY = BODY == null ? null : BODY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.LANDING_PAGE
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.LANDING_PAGE
     */
    public String getLANDING_PAGE() {
        return LANDING_PAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.LANDING_PAGE
     *
     * @param LANDING_PAGE the value for ALRT_PUSH_NOTIFICATION.LANDING_PAGE
     */
    public void setLANDING_PAGE(String LANDING_PAGE) {
        this.LANDING_PAGE = LANDING_PAGE == null ? null : LANDING_PAGE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.NOTIFICATION_DATA
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.NOTIFICATION_DATA
     */
    public String getNOTIFICATION_DATA() {
        return NOTIFICATION_DATA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.NOTIFICATION_DATA
     *
     * @param NOTIFICATION_DATA the value for ALRT_PUSH_NOTIFICATION.NOTIFICATION_DATA
     */
    public void setNOTIFICATION_DATA(String NOTIFICATION_DATA) {
        this.NOTIFICATION_DATA = NOTIFICATION_DATA == null ? null : NOTIFICATION_DATA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.STATUS
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.STATUS
     */
    public String getSTATUS() {
        return STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.STATUS
     *
     * @param STATUS the value for ALRT_PUSH_NOTIFICATION.STATUS
     */
    public void setSTATUS(String STATUS) {
        this.STATUS = STATUS == null ? null : STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.CHANNEL_USER_ID
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.CHANNEL_USER_ID
     */
    public BigDecimal getCHANNEL_USER_ID() {
        return CHANNEL_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.CHANNEL_USER_ID
     *
     * @param OC_CREATED_BY the value for ALRT_PUSH_NOTIFICATION.OC_CREATED_BY
     */
    public void setCHANNEL_USER_ID(BigDecimal CHANNEL_USER_ID) {
        this.CHANNEL_USER_ID = CHANNEL_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.CREATED_DATE
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.CREATED_DATE
     */
    public Date getCREATED_DATE() {
        return CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.CREATED_DATE
     *
     * @param CREATED_DATE the value for ALRT_PUSH_NOTIFICATION.CREATED_DATE
     */
    public void setCREATED_DATE(Date CREATED_DATE) {
        this.CREATED_DATE = CREATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ALRT_PUSH_NOTIFICATION.CHANNEL_USER_NAME
     *
     * @return the value of ALRT_PUSH_NOTIFICATION.CHANNEL_USER_NAME
     */
    public String getCHANNEL_USER_NAME()
    {
        return CHANNEL_USER_NAME;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ALRT_PUSH_NOTIFICATION.CHANNEL_USER_NAME
     *
     * @param CREATED_DATE the value for ALRT_PUSH_NOTIFICATION.CHANNEL_USER_NAME
     */
    public void setCHANNEL_USER_NAME(String CHANNEL_USER_NAME)
    {
        this.CHANNEL_USER_NAME = CHANNEL_USER_NAME;
    }
    
    
}