package com.path.alert.vo.omniservice;
import com.path.vo.common.header.ServiceResponseVO;
import com.path.vo.common.header.ResponseContextVO;
import com.path.vo.common.header.ResponseServiceContextVO;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class SendSMSResp extends ImBaseRequest
 */

@XmlType(propOrder={})
public class SendOmniResp extends ImBaseRequest
{
	private ServiceResponseVO serviceResponse = new ServiceResponseVO();
	private ResponseContextVO responseContext = new ResponseContextVO();
	private ResponseServiceContextVO responseServiceContext = new ResponseServiceContextVO();
	private String as_mobile_phone;
	private String as_message_body;

	public void setServiceResponse(ServiceResponseVO serviceResponse)
	{
	   this.serviceResponse = serviceResponse;
	}
	public ServiceResponseVO getServiceResponse()
	{
	   return serviceResponse;
	}
	public void setResponseContext(ResponseContextVO responseContext)
	{
	   this.responseContext = responseContext;
	}
	public ResponseContextVO getResponseContext()
	{
	   return responseContext;
	}
	public void setResponseServiceContext(ResponseServiceContextVO responseServiceContext)
	{
	   this.responseServiceContext = responseServiceContext;
	}
	public ResponseServiceContextVO getResponseServiceContext()
	{
	   return responseServiceContext;
	}
	public void setAs_mobile_phone(String as_mobile_phone)
	{
	   this.as_mobile_phone = as_mobile_phone;
	}
	public String getAs_mobile_phone()
	{
	   return as_mobile_phone;
	}
	public void setAs_message_body(String as_message_body)
	{
	   this.as_message_body = as_message_body;
	}
	public String getAs_message_body()
	{
	   return as_message_body;
	}
}
