package com.path.alert.vo.smsservice;
import com.path.vo.common.header.ServiceContextAllVO;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlElement;
import com.path.vo.common.ImBaseRequest;
import javax.xml.bind.annotation.XmlType;

/**
 * @AutoGenerated Code
 * @description class SendSMSReq extends ImBaseRequest
 */

@XmlType(propOrder={})
public class SendSMSReq extends ImBaseRequest
{
	private ServiceContextAllVO serviceContext = new ServiceContextAllVO();
	private String as_mobile_phone;
	private String as_message_body;
	private String as_lang_code;
	private BigDecimal an_processed;
	private BigDecimal an_request_id;
	private BigDecimal an_msg_id;
        private BigDecimal code;
        
	public void setServiceContext(ServiceContextAllVO serviceContext)
	{
	   this.serviceContext = serviceContext;
	}
	public ServiceContextAllVO getServiceContext()
	{
	   return serviceContext;
	}
	public void setAs_mobile_phone(String as_mobile_phone)
	{
	   this.as_mobile_phone = as_mobile_phone;
	}
	@XmlElement(required = true)
	public String getAs_mobile_phone()
	{
	   return as_mobile_phone;
	}
	public void setAs_message_body(String as_message_body)
	{
	   this.as_message_body = as_message_body;
	}
	
	@XmlElement(required = true)
	public String getAs_message_body()
	{
	   return as_message_body;
	}

	@XmlElement(required = true)
	public String getAs_lang_code()
	{
	    return as_lang_code;
	}

	public void setAs_lang_code(String as_lang_code)
	{
	    this.as_lang_code = as_lang_code;
	}
	
	public BigDecimal getAn_processed()
	{
	    return an_processed;
	}
	
	public void setAn_processed(BigDecimal an_processed)
	{
	    this.an_processed = an_processed;
	}
	
	@XmlElement(required = true)
	public BigDecimal getAn_request_id()
	{
	    return an_request_id;
	}
	
	@XmlElement(required = true)
	public BigDecimal getAn_msg_id()
	{
	    return an_msg_id;
	}
	
	public void setAn_request_id(BigDecimal an_request_id)
	{
	    this.an_request_id = an_request_id;
	}
	
	public void setAn_msg_id(BigDecimal an_msg_id)
	{
	    this.an_msg_id = an_msg_id;
	}
	
	public BigDecimal getCode()
	{
	    return code;
	}

	public void setCode(BigDecimal code)
	{
	    this.code = code;
	}
	
	
}
